# Generated by Django 3.0.8 on 2021-03-09 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwkAttendants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendant1', models.CharField(blank=True, max_length=50, null=True)),
                ('attendant2', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=50, null=True)),
                ('zone_name', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'swk_attendants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwkTracksheetReport',
            fields=[
                ('num_houses_reached', models.IntegerField()),
                ('num_houses_doing_segg', models.IntegerField()),
                ('num_houses_giving_mixwaste', models.IntegerField()),
                ('drywaste_bf', models.IntegerField()),
                ('drywaste_af', models.IntegerField()),
                ('wetwaste_bf', models.IntegerField()),
                ('wetwaste_af', models.IntegerField()),
                ('lane_name', models.CharField(max_length=200)),
                ('num_attendants', models.IntegerField()),
                ('first_attendants_name', models.CharField(max_length=100)),
                ('second_attendants_name', models.CharField(max_length=100)),
                ('time_of_visit', models.CharField(max_length=100)),
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('supervisor_name', models.CharField(max_length=100)),
                ('num_houses', models.IntegerField(blank=True, null=True)),
                ('rejected_total', models.IntegerField(blank=True, null=True)),
                ('rejected_dry', models.IntegerField(blank=True, null=True)),
                ('rejected_wet', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'swk_tracksheet_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'zones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DutyEntry',
            fields=[
                ('lane_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('first_attendants_name', models.CharField(max_length=100)),
                ('second_attendants_name', models.CharField(max_length=100)),
                ('num_houses_lane', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TracksheetModel',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Tracksheet',
            fields=[
                ('date', models.DateField(help_text='Enter Date')),
                ('lane_name', models.CharField(max_length=200)),
                ('num_attendants', models.CharField(default=2, max_length=10)),
                ('first_attendants_name', models.CharField(max_length=100)),
                ('second_attendants_name', models.CharField(max_length=100)),
                ('supervisor_name', models.CharField(default='Zaheer', max_length=100)),
                ('num_houses_reached', models.IntegerField(default=20, help_text='Enter Houses Reached')),
                ('num_houses_doing_segg', models.IntegerField()),
                ('num_houses_giving_mixwaste', models.IntegerField()),
                ('drywaste_bf', models.IntegerField()),
                ('drywaste_af', models.IntegerField()),
                ('wetwaste_bf', models.IntegerField()),
                ('wetwaste_af', models.IntegerField()),
                ('time_of_visit', models.CharField(max_length=100)),
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('rejected', models.IntegerField()),
                ('zone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swk.Zones')),
            ],
        ),
    ]
