# Generated by Django 3.1.2 on 2020-10-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracksheet',
            name='date',
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='first_attendants_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='lane_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='second_attendants_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='time_of_visit',
            field=models.CharField(max_length=100),
        ),
    ]
