# Generated by Django 3.1.2 on 2020-10-29 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0002_auto_20201029_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksheet',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
