# Generated by Django 3.0 on 2021-01-20 07:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0010_auto_20201217_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('feedback', models.TextField()),
            ],
            options={
                'db_table': 'feedabck',
                'managed': False,
            },
        ),
    ]
