# Generated by Django 3.0 on 2021-01-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0011_feedback'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
    ]
