# Generated by Django 3.0 on 2021-01-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0012_auto_20210120_0747'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='swk_feedback',
        ),
    ]
